export default [
  {
    id: 1,
    title: "Beetlejuice 1",
    Ticket_No:"T0001 1",
    Betting_Time: "1988 1",
    Draw_Date: "92 1",
    Draw_Id: "92 1",
    Bet_Number: "Tim Burton 1",
    Company: "Alec Baldwin, Geena Davis, Annie McEnroe, Maurice Page 1",
    Total:'A couple of recently deceased ghosts contract the services of a ',
    Rebate:"",
    Net: "Tim Burton",
    winning: "Tim Burton",
    Winning_Loss: "Tim Burton"
  },
  {
    id: 2,
    title: "Beetlejuice 2",
    Ticket_No:"T0001 2",
    Betting_Time: "1988",
    Draw_Date: "92",
    Draw_Id: "92",
    Bet_Number: "Tim Burton",
    Company: "Alec Baldwin, Geena Davis, Annie McEnroe, Maurice Page",
    Total:'A couple of recently deceased ghosts contract the services of a ',
    Rebate:"",
    Net: "Tim Burton",
    winning: "Tim Burton",
    Winning_Loss: "Tim Burton"
  },
  {
    id: 3,
    title: "Beetlejuice 3",
    Ticket_No:"T0001 3",
    Betting_Time: "1988",
    Draw_Date: "92",
    Draw_Id: "92",
    Bet_Number: "Tim Burton",
    Company: "Alec Baldwin, Geena Davis, Annie McEnroe, Maurice Page",
    Total:'A couple of recently deceased ghosts contract the services of a ',
    Rebate:"",
    Net: "Tim Burton",
    winning: "Tim Burton",
    Winning_Loss: "Tim Burton"
  },
  {
    id: 4,
    title: "Beetlejuice 4",
    Ticket_No:"T0001 4",
    Betting_Time: "1988",
    Draw_Date: "92",
    Draw_Id: "92",
    Bet_Number: "Tim Burton",
    Company: "Alec Baldwin, Geena Davis, Annie McEnroe, Maurice Page",
    Total:'A couple of recently deceased ghosts contract the services of a ',
    Rebate:"",
    Net: "Tim Burton",
    winning: "Tim Burton",
    Winning_Loss: "Tim Burton"
  },
  {
    id: 5,
    title: "Beetlejuice 5",
    Ticket_No:"T0001 5",
    Betting_Time: "1988",
    Draw_Date: "92",
    Draw_Id: "92",
    Bet_Number: "Tim Burton",
    Company: "Alec Baldwin, Geena Davis, Annie McEnroe, Maurice Page",
    Total:'A couple of recently deceased ghosts contract the services of a ',
    Rebate:"",
    Net: "Tim Burton",
    winning: "Tim Burton",
    Winning_Loss: "Tim Burton"
  },
  {
    id: 6,
    title: "Beetlejuice 6",
    Ticket_No:"T0001 6",
    Betting_Time: "1988",
    Draw_Date: "92",
    Draw_Id: "92",
    Bet_Number: "Tim Burton",
    Company: "Alec Baldwin, Geena Davis, Annie McEnroe, Maurice Page",
    Total:'A couple of recently deceased ghosts contract the services of a ',
    Rebate:"",
    Net: "Tim Burton",
    winning: "Tim Burton",
    Winning_Loss: "Tim Burton"
  },
  {
    id: 7,
    title: "Beetlejuice 7",
    Ticket_No:"T0001 7",
    Betting_Time: "1988",
    Draw_Date: "92",
    Draw_Id: "92",
    Bet_Number: "Tim Burton",
    Company: "Alec Baldwin, Geena Davis, Annie McEnroe, Maurice Page",
    Total:'A couple of recently deceased ghosts contract the services of a ',
    Rebate:"",
    Net: "Tim Burton",
    winning: "Tim Burton",
    Winning_Loss: "Tim Burton"
  },
  {
    id: 8,
    title: "Beetlejuice 8",
    Ticket_No:"T0001 8",
    Betting_Time: "1988",
    Draw_Date: "92",
    Draw_Id: "92",
    Bet_Number: "Tim Burton",
    Company: "Alec Baldwin, Geena Davis, Annie McEnroe, Maurice Page",
    Total:'A couple of recently deceased ghosts contract the services of a ',
    Rebate:"",
    Net: "Tim Burton",
    winning: "Tim Burton",
    Winning_Loss: "Tim Burton"
  },
  {
    id: 9,
    title: "Beetlejuice 9",
    Ticket_No:"T0001 9",
    Betting_Time: "1988",
    Draw_Date: "92",
    Draw_Id: "92",
    Bet_Number: "Tim Burton",
    Company: "Alec Baldwin, Geena Davis, Annie McEnroe, Maurice Page",
    Total:'A couple of recently deceased ghosts contract the services of a ',
    Rebate:"",
    Net: "Tim Burton",
    winning: "Tim Burton",
    Winning_Loss: "Tim Burton"
  },
  {
    id: 10,
    title: "Beetlejuice 10",
    Ticket_No:"T0001 10",
    Betting_Time: "1988",
    Draw_Date: "92",
    Draw_Id: "92",
    Bet_Number: "Tim Burton",
    Company: "Alec Baldwin, Geena Davis, Annie McEnroe, Maurice Page",
    Total:'A couple of recently deceased ghosts contract the services of a ',
    Rebate:"",
    Net: "Tim Burton",
    winning: "Tim Burton",
    Winning_Loss: "Tim Burton"
  },
  
  
];