import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="navbar navbar-expand-lg justify-content-center"> 
        <div className="container-fluid">
          <a className="navbar-brand" href="#">
          <img src="img/LOGO MALAYSIA BACK-01.png"  width="150" height="74" ></img>
          </a>
          <div className="collapse navbar-collapse" id="navbarNav" style={{display:'flex', justifyContent: 'space-between', alignItems: 'flex-end' }}>
            <ul className="navbar-nav">
              <li className="nav-item">
                <a className="nav-link" aria-current="page" href="#">Home</a>
              </li>
              <li className="nav-item">
                <a className="nav-link" href="#">Bettting</a>
              </li>
              <li className="nav-item">
                <a className="nav-link" href="#">History</a>
              </li>
              <li className="nav-item">
                <a className="nav-link">Results</a>
              </li>
            </ul>
          </div>
          <div className=" navbar-nav me-auto mb-2 mb-lg-0">
          <ul className="navbar-nav flex-row d-none d-md-flex " >
              <li className="nav-item">
                <a className="nav-link">
                  John_0786
                  <br/>
                  102,84665.00 <button className="btn btn-warning btn-sm rounded-pill">VND</button>
                  </a>
              </li>
            </ul>
          </div>
          <div className=" navbar-nav me-auto mb-2 mb-lg-0">
            
            <form class="form-inline my-2 my-lg-0">
                <button className="btn btn-warning  form-control mr-sm-2">PLAY LOTTERY</button>
            </form>
            <ul className='navbar-nav  '>
                 <li className='nav-item'>
                <a className='nav-link'><img
            src="img/photo_2022-09-28 16.33.50.jpeg"
            className="rounded-circle"
            height="20"
            loading="lazy"
          /></a>
              </li>
              <li className='nav-item'>
                <a className='nav-link'>ENG!</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      
      <main className={styles.main}>
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1> */}

      {/* <div className='card container'>
          <div className="card-header" style={{display:'flex', justifyContent: 'space-between', alignItems: 'flex-end' }}>
           <div className='d-flex'>
            <img src="img/delete.png" style={{width:'48px'}}></img>
            <div className='d-flex flex-column px-3' >
              <b>Sushil</b>
              <span>Credit: <b>2600 VND</b></span> 
            </div>
           </div>
          <div>
            <p href="#" className="card-link">Transaction History</p>
          </div>
          </div>
      </div> */}

      <div className='d-flex justify-content-center'>
        <img className={styles.selectBet} src="img/Red_3d.png"></img>
        <img className={styles.selectBet} src="img/Yellow_4d.png"></img>
      </div>

      <form className='row container'>
        <div className="form-check form-check-inline col" style={{border: '2px solid red', padding: '30px', borderRadius: '50px 0px'}}>
          <input  className="form-check-input" name='bet_date' type="checkbox" id="option1"/>
          <label className='d-flex flex-column'>
                <b>Tuesday</b>
                <span>20 Sep 2022</span> 
          </label>
          <img style={{maxWidth:'30px'}} src="img/logo da MACAI.png"></img>
          <img style={{maxWidth:'30px'}} src="img/LOGO Magnum.png"></img>
          <img style={{maxWidth:'30px'}} src="img/LOGO TOTO.png"></img>
        </div>
        <div className="form-check form-check-inline col" style={{border: '2px solid red', padding: '30px', borderRadius: '50px 0px'}}>
          <input  className="form-check-input" name='bet_date' type="checkbox" id="option2"/>
          <label className='d-flex flex-column'>
                <b>Tuesday</b>
                <span>20 Sep 2022</span> 
          </label>
          <img style={{maxWidth:'30px'}} src="img/logo da MACAI.png"></img>
          <img style={{maxWidth:'30px'}} src="img/LOGO Magnum.png"></img>
          <img style={{maxWidth:'30px'}} src="img/LOGO TOTO.png"></img>
        </div>
        <div className="form-check form-check-inline col" style={{border: '2px solid red', padding: '30px', borderRadius: '50px 0px'}}>
          <input  className="form-check-input" name='bet_date' type="checkbox" id="option3"/>
          <label className='d-flex flex-column'>
                <b>Tuesday</b>
                <span>20 Sep 2022</span> 
          </label>
          <img style={{maxWidth:'30px'}} src="img/logo da MACAI.png"></img>
          <img style={{maxWidth:'30px'}} src="img/LOGO Magnum.png"></img>
          <img style={{maxWidth:'30px'}} src="img/LOGO TOTO.png"></img>
        </div>
        <div className="form-check form-check-inline col" style={{border: '2px solid red', padding: '30px', borderRadius: '50px 0px'}}>
          <input  className="form-check-input" name='bet_date' type="checkbox" id="option4"/>
          <label className='d-flex flex-column'>
                <b>Tuesday</b>
                <span>20 Sep 2022</span> 
          </label>
          <img style={{maxWidth:'30px'}} src="img/logo da MACAI.png"></img>
          <img style={{maxWidth:'30px'}} src="img/LOGO Magnum.png"></img>
          <img style={{maxWidth:'30px'}} src="img/LOGO TOTO.png"></img>
        </div>
      </form>

        <table className='table container'>
          <thead className='border-white'>
            <tr className='text-center'>
              <th></th>
            <th>Number</th>
            <th>Big/3A</th>
            <th>Small/3C</th>
            <th>Bet Type</th>
            <th>Amount</th>
            </tr>
          </thead>
          <tbody >
           <tr>
             <th>
              <div className={styles.betTableNumber}>
                  1
                </div>
             </th>
             <td>
               <input className='form-control' type="text" style={{border: '1px solid red', borderRadius: '20px 0px'}}/>
             </td>
             <td>
               <input className='form-control' type="text" style={{border: '1px solid red', borderRadius: '20px 0px'}}/>
             </td>
             <td>
               <input className='form-control' type="text" style={{border: '1px solid red', borderRadius: '20px 0px'}}/>
             </td>
             <td className=''>
              {/* <input  className="form-check-input" name='bet_date' type="checkbox" id="option1"/> */}

               <input className="form-check-input form-check-inline col" type="checkbox" id="B" style={{border: '1px solid red', padding: '20px', borderRadius: '20px 0px', maxWidth:"50px"}}>
               </input>
               <input className="form-check-input form-check-inline col" type="checkbox" id="I" style={{border: '1px solid red', padding: '20px', borderRadius: '20px 0px', maxWidth:"50px"}}>
               </input>
               <input className="form-check-input form-check-inline col" type="checkbox" id="R" style={{border: '1px solid red', padding: '20px', borderRadius: '20px 0px', maxWidth:"50px"}}>
               </input>
             </td>
             <td>
                 <input className='form-control' type="text" style={{border: '1px solid red', borderRadius: '20px 0px'}}/>
             </td>
             <td>
               <img style={{maxWidth:'30px'}} src="img/delete.png"></img>
             </td>
           </tr>
           <tr>
             <th>
              {/* <div className={`${styles.betTableNumber} form-check form-check-inline col`}> */}
              <div className={styles.betTableNumber}>
                2
              </div>
             </th>
             <td>
               <input className='form-control' type="text" style={{border: '1px solid red', borderRadius: '20px 0px'}}/>
             </td>
             <td>
               <input className='form-control' type="text" style={{border: '1px solid red', borderRadius: '20px 0px'}}/>
             </td>
             <td>
               <input className='form-control' type="text" style={{border: '1px solid red', borderRadius: '20px 0px'}}/>
             </td>
             <td >
              <input className="form-check-input form-check-inline col" type="checkbox" id="B" style={{border: '1px solid red', padding: '20px', borderRadius: '20px 0px', maxWidth:"50px"}}>
               </input>
               <input className="form-check-input form-check-inline col" type="checkbox" id="I" style={{border: '1px solid red', padding: '20px', borderRadius: '20px 0px', maxWidth:"50px"}}>
               </input>
               <input className="form-check-input form-check-inline col" type="checkbox" id="R" style={{border: '1px solid red', padding: '20px', borderRadius: '20px 0px', maxWidth:"50px"}}>
               </input>
             </td>
             <td>
                 <input className='form-control' type="text" style={{border: '1px solid red', borderRadius: '20px 0px'}}/>
             </td>
             <td>
               <img style={{maxWidth:'30px'}} src="img/delete.png"></img>
             </td>
           </tr>
          </tbody>
        </table>
        <div className={`${styles.betTotal} container`} >
              <div>
                <b>
                  Total Stake
                </b>
                <label className='px-3'>
                  216.00
                </label>
              </div>
            <div>
              <button type="button" className={`${styles.boxStyle} mx-5`} style={{background:'white',fontWeight:'bold',padding: '10px 30px'}}>
                Cancel
              </button>
              <button type="button" className={`${styles.boxStyle}`} style={{background:'#bf2262' ,fontWeight:'bold' ,color:'white'}}>
                Check & Continue
              </button>
            </div>
          </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/img/hero-building.png" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
