import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className="navbar navbar-expand-lg justify-content-center"> 
        <div className="container-fluid">
          <a className="navbar-brand" href="#">
          <img src="img/LOGO MALAYSIA BACK-01.png"  width="150" height="74" ></img>
          </a>
          <div className="collapse navbar-collapse" id="navbarNav" style={{display:'flex', justifyContent: 'space-between', alignItems: 'flex-end' }}>
            <ul className="navbar-nav">
              <li className="nav-item">
                <a className="nav-link" aria-current="page" href="#">Home</a>
              </li>
              <li className="nav-item">
                <a className="nav-link" href="#">Bettting</a>
              </li>
              <li className="nav-item">
                <a className="nav-link" href="#">History</a>
              </li>
              <li className="nav-item">
                <a className="nav-link">Results</a>
              </li>
            </ul>
          </div>
          <div className=" navbar-nav me-auto mb-2 mb-lg-0">
          <ul className="navbar-nav flex-row d-none d-md-flex " >
              <li className="nav-item">
                <a className="nav-link">
                  John_0786
                  <br/>
                  102,84665.00 <button className="btn btn-warning btn-sm rounded-pill">VND</button>
                  </a>
              </li>
            </ul>
          </div>
          <div className=" navbar-nav me-auto mb-2 mb-lg-0">
            
            <form class="form-inline my-2 my-lg-0">
                <button className="btn btn-warning  form-control mr-sm-2">PLAY LOTTERY</button>
            </form>
            <ul className='navbar-nav  '>
                 <li className='nav-item'>
                <a className='nav-link'><img
            src="img/photo_2022-09-28 16.33.50.jpeg"
            className="rounded-circle"
            height="20"
            loading="lazy"
          /></a>
              </li>
              <li className='nav-item'>
                <a className='nav-link'>ENG</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      
      <main className={styles.main}>

      <div className='card container'>
          <div className="card-header" style={{display:'flex', justifyContent: 'space-between', alignItems: 'flex-end' }}>
           <img src="img/delete.png" style={{width:'20px'}}></img>
           <div className='d-flex flex-column' >
             <b>Sushil</b>
             <span>Credit: <b>2600 VND</b></span> 
             
           </div>
          <div>
            <p href="#" className="card-link">Transaction History</p>
          </div>
          </div>
         
      </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/img/hero-building.png" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
